version: "3.8"

services:
  app:
    image: ghcr.io/enzomoy/focus:latest
    container_name: focus-app
    restart: unless-stopped
    ports:
      - "3333:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
